### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by codrin-iftimie** [GoogleCloudPlatform/gke-network-policy-demo#33]
The readme has a typo where it expects 
```
 networkPolicyConfig:
    disabled: true
--
networkPolicy:
  provider: CALICO
```
In the code we have https://github.com/GoogleCloudPlatform/gke-network-policy-demo/blob/master/terraform/main.tf#L87

Actual behaviour
```
networkPolicyConfig: {}
clusterIpv4Cidr: 10.0.92.0/22
--
networkPolicy:
  enabled: true
```
